version: '3'

services:
  backend:
    build:
      context: ./antit_back
    ports:
      - "8000:8000"
    volumes:
      - ./antit_back:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - POSTGRES_DB=antit_db
      - POSTGRES_USER=antit_user
      - POSTGRES_PASSWORD=antit_pass
    env_file:
      - ./antit_back/antit_back/.env

  frontend:
    build:
      context: ./antit_front
    ports:
      - "8080:8080"
    volumes:
      - ./antit_front:/app

  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data_db:rw
    environment:
      POSTGRES_DB: 'antit_db'
      POSTGRES_USER: 'antit_user'
      POSTGRES_PASSWORD: 'antit_pass'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      PGDATA: '/var/lib/postgresql/data/'
    ports:
      - "5432:5432"

volumes:
  db_data:
