version: '3'

services:
  backend:
    build:
      context: ./antit_back
      dockerfile: ./antit_back/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./antit_back:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - POSTGRES_DB=antit_db
      - POSTGRES_USER=antit_user
      - POSTGRES_PASSWORD=
    env_file:
      - ./antitback/antit_back/.env

  frontend:
    build:
      context: ./antit_front
      dockerfile: ./antit_front/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./antit_front:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'antit_db'
      POSTGRES_USER: 'antit_user'
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
